force-app/main/default/objects/Product_Instance__c/Product_Instance__c.object-meta.xml
<CustomObject>
    <label>Product Instance</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Instance_Usage__c/Product_Instance_Usage__c.object-meta.xml
<CustomObject>
    <label>Product Instance Usage</label>
    <nameField>
        <displayFormat>Usage-{00000}</displayFormat>
        <label>Usage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Instances Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Instance_Usage__c/fields/Product_Instance__c.field-meta.xml
<CustomField>
    <fullName>Product_Instance__c</fullName>
    <label>Product Instance</label>
    <referenceTo>Product_Instance__c</referenceTo>
    <relationshipLabel>Product Instances Usage</relationshipLabel>
    <relationshipName>Product_Instances_Usage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Instance_Usage__c/fields/Usage_Count__c.field-meta.xml
<CustomField>
    <fullName>Usage_Count__c</fullName>
    <label>Usage Count</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Instance_Usage__c/fields/Usage_Period__c.field-meta.xml
<CustomField>
    <fullName>Usage_Period__c</fullName>
    <label>Usage Period</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ProductInstanceUsageChartController.cls
public class ProductInstanceUsageChartController {
    
    @AuraEnabled(cacheable=true)
    public static List<Product_Instance_Usage__c> fetchAllUsageRecords(string insatnceId){
        List<Product_Instance_Usage__c> usageRecords=[SELECT Id,Product_Instance__c, Usage_Count__c, Usage_Period__c, Name FROM Product_Instance_Usage__c where Product_Instance__c=:insatnceId];
        return usageRecords;
    }

}