force-app/main/default/objects/Field_History_Tracker__c/Field_History_Tracker__c.object-meta.xml
<CustomObject>
    <label>Field History Tracker</label>
    <nameField>
        <displayFormat>Track-{00000000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fields History Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History_Tracker__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <inlineHelpText>Api name of field</inlineHelpText>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Api Name of Object</inlineHelpText>
    <label>Object</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Relation__c.field-meta.xml
<CustomField>
    <fullName>Relation__c</fullName>
    <label>Relation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Record</fullName>
            </value>
            <value>
                <fullName>Child Object</fullName>
            </value>
            <value>
                <fullName>Parent Object</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fields_History_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/History_Tracker__mdt/History_Tracker__mdt.object-meta.xml
<CustomObject>
    <description>Field History And Usage Tracker Configuration</description>
    <label>History Tracker</label>
    <pluralLabel>History Tracker</pluralLabel>
</CustomObject>

force-app/main/default/objects/History_Tracker__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <inlineHelpText>Api Name of fields</inlineHelpText>
    <label>Fields</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/History_Tracker__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>API Name of object</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Tracker__mdt/fields/Track_Fields__c.field-meta.xml
<CustomField>
    <fullName>Track_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Fields</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/Tracking_Events__e.object-meta.xml
<CustomObject>
    <description>Event To Receive changes published by after trigger on record change</description>
    <label>Tracking Event</label>
    <pluralLabel>Tracking Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tracking_Events__e/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/fields/Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Name__c</fullName>
    <label>Record Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrackHistory.cls
public inherited sharing class TrackHistory {
    @future 
    public static void track(String objectName,String newRecordsListJSON,string oldRecordsMapJSON){
        System.debug('TrackHistory=>track');
        List<sObject> newRecords=(List<sObject>)JSON.deserialize(newRecordsListJSON, List<sObject>.class);
        Map<id,sObject> oldRecords=(Map<id,sObject>)JSON.deserialize(oldRecordsMapJSON, Map<id,sObject>.class);
        List<String> fields=getFieldsToTrack(objectName);
        if(fields.size()==0) return;
        List<Field_History_Tracker__c> toInsertRecords=new List<Field_History_Tracker__c>();
        //Obtaining schema of object and fields
        DescribeSobjectResult objectDetails=SchemaUtility.getSobjectType(objectName);
        Map<String,DescribeFieldResult> fieldDetails=SchemaUtility.getAllObjectFields(objectDetails);
        
        for(sObject record:newRecords){
            sObject oldRecord=oldRecords.get((Id)record.get('Id'));
            for(String field:fields){
                //checking if field value is changed 
                if(record.getPopulatedFieldsAsMap().containsKey(field) && record.get(field)!=oldRecord.get(field)){
                    Field_History_Tracker__c change=new Field_History_Tracker__c();
                    change.Field__c=field;
                    change.Field_Label__c=fieldDetails.get(field).getLabel();
                    change.Object_Label__c=objectDetails.getLabel();
                    change.Object__c=objectName;
                    change.Record_Id__c=(Id)record.get('Id');
                    change.Old_Value__c=String.valueOf(oldRecord.get(field));
                    change.New_Value__c=String.valueOf(record.get(field));
                    change.Record_Name__c=String.valueOf(record.get(getFieldApiForName(objectName)));
                    change.Relation__c='On Record';
                    change.User__c=Userinfo.getUserId();
                    change.RecordTypeId=Constant.TRACK_FIELD_CHANGE_RECORDTYPE_ID;
                    toInsertRecords.add(change);
                }
            }
        }
        if(toInsertRecords.size()>0) insert toInsertRecords;
    }
    
    public static void captureChanges(List<Tracking_Events__e> changes){
        //creating map of object and schema
        Map<String,DescribeSobjectResult> objectDescriptionMap=new Map<String,DescribeSobjectResult>();
        Map<String,Map<String,DescribeFieldResult>> objectFieldsMap=new Map<String,Map<String,DescribeFieldResult>>();
        for(Tracking_Events__e event:changes){
            if(!objectDescriptionMap.containsKey(event.Object__c)){
                objectDescriptionMap.put(event.Object__c,null);
            }
            if(!objectFieldsMap.containsKey(event.Object__c)){
                objectFieldsMap.put(event.Object__c,null);
            }
        }
        //Obtaining schema of object and fields
        for(String objectName:objectDescriptionMap.keySet()){
            DescribeSobjectResult objectDetails=SchemaUtility.getSobjectType(objectName);
            objectDescriptionMap.put(objectName,objectDetails);
            objectFieldsMap.put(objectName,SchemaUtility.getAllObjectFields(objectDetails));
        }
        List<Field_History_Tracker__c> toInsertRecords=new List<Field_History_Tracker__c>();
        //create Records
        for(Tracking_Events__e event:changes){
            Field_History_Tracker__c change=new Field_History_Tracker__c();
            change.Relation__c='On Record';
            change.RecordTypeId=Constant.TRACK_FIELD_CHANGE_RECORDTYPE_ID;
            change.Field__c=event.Field__c;
            change.Object__c=event.Object__c;
			change.Record_Id__c=event.Record_Id__c;
            change.Old_Value__c=event.Old_Value__c;
            change.New_Value__c=event.New_Value__c;
            change.Record_Name__c=event.Record_Name__c;
            change.User__c=event.User_Id__c;
            if(objectDescriptionMap.containsKey(event.Object__c)) change.Field_Label__c=objectDescriptionMap.get(event.Object__c).getLabel();
            if(objectFieldsMap.containsKey(event.Object__c)) change.Object_Label__c=objectFieldsMap.get(event.Object__c).get(event.Field__c).getLabel();
            toInsertRecords.add(change);
        }
        if(toInsertRecords.size()>0) insert toInsertRecords;
        
    }
    
    public static void publishChanges(String objectName,List<sObject> newRecords,Map<id,sObject> oldRecords){
        //check configuration
        List<String> fields=getFieldsToTrack(objectName);
        if(fields.size()==0) return;
        List<Tracking_Events__e> toPublishRecords=new List<Tracking_Events__e>();
        for(sObject record:newRecords){
            sObject oldRecord=oldRecords.get((Id)record.get('Id'));
            for(String field:fields){
                //checking if field value is changed 
                if(record.getPopulatedFieldsAsMap().containsKey(field) && record.get(field)!=oldRecord.get(field)){
                    Tracking_Events__e e=New Tracking_Events__e();
                    e.Field__c=field;
                    e.Object__c=objectName;
                    e.Record_Id__c=String.valueOf(record.get('Id'));
                    e.Record_Name__c=String.valueOf(record.get(getFieldApiForName(objectName)));
                    e.New_Value__c=String.valueOf(record.get(field));
                    e.Old_Value__c=String.valueOf(oldRecord.get(field));
                    e.User_Id__c=Userinfo.getUserId();
                    toPublishRecords.add(e);
                }
            }
        }
        if(toPublishRecords.size()>0) EventBus.publish(toPublishRecords);
    }
    
       
    private static List<String> getFieldsToTrack(String ObjectName){
        //get field names that needs to be tracked
        List<History_Tracker__mdt> fieldConfig=[SELECT Fields__c FROM History_Tracker__mdt WHERE DeveloperName=:ObjectName AND Track_Fields__c=True];
        List<String> fields=new List<String>();
        if(fieldConfig.size()>0) fields=fieldConfig.get(0).Fields__c.split(',');
        return fields;
    }
    
    private static String getFieldApiForName(String objectName){
        String name='Name';
        if(objectName=='Task' || objectName=='Event' ) name='Subject';
        if(objectName=='Case') name='CaseNumber';
        return name;
    }

    
    
}