force-app/main/default/objects/Field_History_Tracker__c/Field_History_Tracker__c.object-meta.xml
<CustomObject>
    <label>Field History Tracker</label>
    <nameField>
        <displayFormat>Track-{00000000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fields History Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History_Tracker__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Api Name of Object</inlineHelpText>
    <label>Object</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Record__c.field-meta.xml
<CustomField>
    <fullName>Record__c</fullName>
    <formula>HYPERLINK(&#39;/lightning/r/&#39;+ Object__c +&#39;/&#39;+Record_Id__c+&#39;/view&#39;,  Record_Name__c )</formula>
    <label>Record</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatedHistoryController.cls
public class RelatedHistoryController {
    
    @AuraEnabled
    public static List<Field_History_Tracker__c> fetchRecordHistory(Final String recordId,Final String objectName){
        List<Field_History_Tracker__c> history= [SELECT Id, Name, CreatedDate, CreatedById,CreatedBy.Name,LastModifiedDate, LastModifiedById, 
                                                 Object__c, Record_Id__c, Record_Name__c, Field_Label__c, Old_Value__c, New_Value__c, Record__c 
                                                 FROM Field_History_Tracker__c WHERE Record_Id__c=:recordId AND Object__c=:objectName ORDER BY CreatedDate];
        return history;
    }

}