force-app/main/default/objects/Field_History_Tracker__c/Field_History_Tracker__c.object-meta.xml
<CustomObject>
    <label>Field History Tracker</label>
    <nameField>
        <displayFormat>Track-{00000000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fields History Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History_Tracker__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Api Name of Object</inlineHelpText>
    <label>Object</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fields_History_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/History_Tracker__mdt/History_Tracker__mdt.object-meta.xml
<CustomObject>
    <description>Field History And Usage Tracker Configuration</description>
    <label>History Tracker</label>
    <pluralLabel>History Tracker</pluralLabel>
</CustomObject>

force-app/main/default/objects/History_Tracker__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>API Name of object</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Tracker__mdt/fields/Track_Usage__c.field-meta.xml
<CustomField>
    <fullName>Track_Usage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Usage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LogUsageController.cls
public with sharing class LogUsageController {
    
    @AuraEnabled 
    public static void logEntry(String recordId,String objectName){
        //Check for status
        List<History_Tracker__mdt> fieldConfig=[SELECT Id FROM History_Tracker__mdt WHERE DeveloperName=:objectName AND Track_Usage__c=True];
        if(fieldConfig.size()==0) return;
        //Check if record created in past 5 min
        DateTime pastFiveMin=DateTime.now();
        pastFiveMin=pastFiveMin.addMinutes(-5);  
        List<Field_History_Tracker__c> exsists=[SELECT id FROM Field_History_Tracker__c WHERE Record_Id__c=:recordId AND CreatedDate>=:pastFiveMin AND User__c=:userinfo.getUserId()];
        if(exsists.size()>0) return;
        //query record name 
        String name='Name';
        if(objectName=='Task' || objectName=='Event' ) name='Subject';
        if(objectName=='Case') name='CaseNumber';
        if(objectName=='Contact') name='LastName';
        String query='SELECT Id,'+name+' FROM '+objectName+' WHERE Id=:recordId';
        List<Sobject> result=database.query(query);
        if(result.size()==0) return;
        //get object details
        DescribeSobjectResult objectDetails=SchemaUtility.getSobjectType(objectName);
        Field_History_Tracker__c log=new Field_History_Tracker__c();
        //insert log
        log.Object_Label__c=objectDetails.getLabel();
        log.Object__c=objectName;
        log.User__c=Userinfo.getUserId();
        log.Record_Id__c=String.valueOf(result.get(0).get('Id'));
        log.Record_Name__c=String.valueOf(result.get(0).get(name));
        log.RecordTypeId=Constant.TRACK_USAGE_HISTORY_RECORDTYPE_ID;
		insert log;
    }

}