force-app/main/default/objects/Field_History_Tracker__c/Field_History_Tracker__c.object-meta.xml
<CustomObject>
    <label>Field History Tracker</label>
    <nameField>
        <displayFormat>Track-{00000000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fields History Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History_Tracker__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <inlineHelpText>Api name of field</inlineHelpText>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Api Name of Object</inlineHelpText>
    <label>Object</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Relation__c.field-meta.xml
<CustomField>
    <fullName>Relation__c</fullName>
    <label>Relation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Record</fullName>
            </value>
            <value>
                <fullName>Child Object</fullName>
            </value>
            <value>
                <fullName>Parent Object</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RelatedHistoryControllerTest.cls
@isTest
public class RelatedHistoryControllerTest {

    @isTest
    static void fetchRecordHistoryTest(){
        Account a=TestDataFactory.getStandardAccount(true);
        Field_History_Tracker__c change=new Field_History_Tracker__c();
        change.Field__c='Name';
        change.Field_Label__c='Name';
        change.Object_Label__c='Account';
        change.Object__c='Account';
        change.Record_Id__c=a.Id;
        change.Old_Value__c='';
        change.New_Value__c=a.Name;
        change.Record_Name__c=a.Name;
        change.Relation__c='On Record';
        change.RecordTypeId=Constant.TRACK_FIELD_CHANGE_RECORDTYPE_ID;
        insert change;
        List<Field_History_Tracker__c>  records=RelatedHistoryController.fetchRecordHistory(a.Id, 'Account');
        system.assertEquals(a.Name, records.get(0).New_Value__c);
    }
}