force-app/main/default/objects/Field_History_Tracker__c/Field_History_Tracker__c.object-meta.xml
<CustomObject>
    <label>Field History Tracker</label>
    <nameField>
        <displayFormat>Track-{00000000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fields History Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History_Tracker__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <inlineHelpText>Api name of field</inlineHelpText>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Api Name of Object</inlineHelpText>
    <label>Object</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History_Tracker__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Record Id for Administration Purposes</description>
    <formula>CASESAFEID(Id)</formula>
    <inlineHelpText>Record Id for Administration Purposes</inlineHelpText>
    <label>Record Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/Tracking_Events__e.object-meta.xml
<CustomObject>
    <description>Event To Receive changes published by after trigger on record change</description>
    <label>Tracking Event</label>
    <pluralLabel>Tracking Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tracking_Events__e/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tracking_Events__e/fields/Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Name__c</fullName>
    <label>Record Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrackHistoryTest.cls
@isTest
public class TrackHistoryTest {
    
    @testSetup
    static void setupData(){
        Account a=TestDataFactory.getStandardAccount(true);
        Opportunity o=TestDataFactory.getFinleapInvestmentOpportunity(a.Id,true);
    }
    
    @isTest
    static void trackTest(){
        Test.startTest();
        List<Account> o=[select Id,Name FROM Account];
        String newList=JSON.serialize(o);
        Map<Id,Account> oldO=new Map<Id,Account>(o);
        oldO.get(o.get(0).Id).Name='Changed';
        TrackHistory.track('Account',newList,JSON.serialize(oldO));
        Test.stopTest();
        List<Field_History_Tracker__c> newRecords=[SELECT id FROM Field_History_Tracker__c];
        System.assert(newRecords.size()==1);
    }
    
    @isTest
    static void publishChangesTest(){
        Test.startTest();
        List<Account> o=[select Id,Name FROM Account];
        Map<Id,Account> oldO=new Map<Id,Account>(o);
        oldO.get(o.get(0).Id).Name='Changed';
        TrackHistory.publishChanges('Account',o,oldO);
        Test.stopTest();
    }
     @isTest
    static void captureChangesTest(){
        Test.startTest();
        Account  a=[select Id,Name FROM Account LIMIT 1];
        Tracking_Events__e e=New Tracking_Events__e();
        e.Field__c='Name';
        e.Object__c='Account';
        e.Record_Id__c=a.Id;
        e.Record_Name__c=a.Name;
        e.New_Value__c=a.Name;
        e.Old_Value__c='Changed';
        e.User_Id__c=Userinfo.getUserId();
        TrackHistory.captureChanges(new List<Tracking_Events__e>{e});
        Test.stopTest();
        List<Field_History_Tracker__c> newRecords=[SELECT id FROM Field_History_Tracker__c];
        System.assert(newRecords.size()==1);
    }
    
}