force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country where this Account is Located</description>
    <inlineHelpText>Country where this Account is Located</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Customer Type</description>
    <inlineHelpText>Customer Type</inlineHelpText>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Software</fullName>
            </value>
            <value>
                <fullName>Account Switching</fullName>
            </value>
            <value>
                <fullName>Adminstration &amp; Regulators</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Agencies &amp; Events</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Banking App</fullName>
            </value>
            <value>
                <fullName>Brokerage &amp; Investment</fullName>
            </value>
            <value>
                <fullName>Comparison Portal</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Credit Bureaus &amp; Scoring</fullName>
            </value>
            <value>
                <fullName>Datacenter</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Factoring</fullName>
            </value>
            <value>
                <fullName>Fintech</fullName>
            </value>
            <value>
                <fullName>Incubator</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Insurtech</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>ISV/SaaS</fullName>
            </value>
            <value>
                <fullName>Lending</fullName>
            </value>
            <value>
                <fullName>Loans &amp; Debts Collector</fullName>
            </value>
            <value>
                <fullName>Merchant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment &amp; P2P</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>PSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Form__c.field-meta.xml
<CustomField>
    <fullName>Legal_Form__c</fullName>
    <description>Please enter the legal form of the partner company as it is required in our compliance guideline for partners.</description>
    <inlineHelpText>Please enter the legal form of the partner company as it is required in our compliance guideline for partners.</inlineHelpText>
    <label>Legal Form</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finleap_Company__c.field-meta.xml
<CustomField>
    <fullName>Finleap_Company__c</fullName>
    <description>Please select the respective Finleap Company.</description>
    <inlineHelpText>Please select the respective Finleap Company.</inlineHelpText>
    <label>Finleap Company</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finleap Connect</fullName>
            </value>
            <value>
                <fullName>Element</fullName>
            </value>
            <value>
                <fullName>elinvar</fullName>
            </value>
            <value>
                <fullName>solarisBank</fullName>
            </value>
            <value>
                <fullName>BillFront</fullName>
            </value>
            <value>
                <fullName>Clark</fullName>
            </value>
            <value>
                <fullName>Crosslend</fullName>
            </value>
            <value>
                <fullName>financeAds</fullName>
            </value>
            <value>
                <fullName>Joonko</fullName>
            </value>
            <value>
                <fullName>PAIR Finance</fullName>
            </value>
            <value>
                <fullName>Penta</fullName>
            </value>
            <value>
                <fullName>Perseus</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Beesy</fullName>
            </value>
            <value>
                <fullName>Consumer Platform</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Deutsche Fintech Solutions</fullName>
            </value>
            <value>
                <fullName>European Fintech Fund</fullName>
            </value>
            <value>
                <fullName>Figo</fullName>
            </value>
            <value>
                <fullName>Finleap</fullName>
            </value>
            <value>
                <fullName>FinReach</fullName>
            </value>
            <value>
                <fullName>Finreach Solutions</fullName>
            </value>
            <value>
                <fullName>Infinitec Solutions</fullName>
            </value>
            <value>
                <fullName>MoneyMap</fullName>
            </value>
            <value>
                <fullName>ReloadFinance</fullName>
            </value>
            <value>
                <fullName>SBOT</fullName>
            </value>
            <value>
                <fullName>SME Banking</fullName>
            </value>
            <value>
                <fullName>Superr</fullName>
            </value>
            <value>
                <fullName>Valendo</fullName>
            </value>
            <value>
                <fullName>Zinsbaustein</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Product_Vertical__c</fullName>
    <description>Choose a Product Vertical for this Opportunity</description>
    <inlineHelpText>Choose a Product Vertical for this Opportunity</inlineHelpText>
    <label>Product Vertical</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>White-Label Products</fullName>
            </value>
            <value>
                <fullName>Micro Products</fullName>
            </value>
            <value>
                <fullName>Consulting service</fullName>
            </value>
            <value>
                <fullName>Corporate Ventures &amp; Solutions</fullName>
            </value>
            <value>
                <fullName>Data Services</fullName>
            </value>
            <value>
                <fullName>Core Services</fullName>
            </value>
            <value>
                <fullName>Salary Backed Loans</fullName>
            </value>
            <value>
                <fullName>Clark - Insurance manager</fullName>
            </value>
            <value>
                <fullName>Element - Innovative insurance products - API</fullName>
            </value>
            <value>
                <fullName>Element - Innovative insurance products - Plug&amp;Play</fullName>
            </value>
            <value>
                <fullName>Element - Standard insurance products - API</fullName>
            </value>
            <value>
                <fullName>Element - Standard insurance products - Plug&amp;Play</fullName>
            </value>
            <value>
                <fullName>Elinvar - Wealth Management</fullName>
            </value>
            <value>
                <fullName>FinanceAds - Online marketing / Acquisition</fullName>
            </value>
            <value>
                <fullName>PairFinance - Debt collection and white label dunning</fullName>
            </value>
            <value>
                <fullName>Perseus - Cybersecurity Department as a Service</fullName>
            </value>
            <value>
                <fullName>solarisBank - Blockchain Factory</fullName>
            </value>
            <value>
                <fullName>solarisBank - Cards</fullName>
            </value>
            <value>
                <fullName>solarisBank - Digital Banking</fullName>
            </value>
            <value>
                <fullName>solarisBank - KYC Platform</fullName>
            </value>
            <value>
                <fullName>solarisBank - Lending</fullName>
            </value>
            <value>
                <fullName>solarisBank - Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-live/main/default/classes/TestDataFactory.cls
public class TestDataFactory {
    
    //Generator
    public static Account getStandardAccount(Final Boolean isInsert){
        return getAccount(Constant.ACCOUNT_STANDARD_RECORDTYPE_ID,isInsert);
    }
    public static Contact getStandardContact(Final String accountId,Final Boolean isInsert){
        return getContact(Constant.CONTACT_STANDARD_RECORDTYPE_ID,accountId,isInsert);
    }
    public static Opportunity getFinleapInvestmentOpportunity(Final String accountId,Final Boolean isInsert){
        return getOpportunity(Constant.OPPORTUNITY_INVESTMENT_IN_FINLEAP_RECORDTYPE_ID,accountId,isInsert);
    }
     public static Opportunity getFinleapStandardOpportunity(Final String accountId,Final Boolean isInsert){
        return getOpportunity(Constant.OPPORTUNITY_STANDARD_SALES_RECORDTYPE_ID,accountId,isInsert);
    }
    
    public static User getCommunicationsUser(Final Boolean isInsert){
        return getUser(Constant.COMMUNICATION_PROFILE_ID,isInsert);
    }
   
    public static void addOpportunityToContact(String oppId,String contactId){
        getOpportunityContactRole(contactId,oppId,true);
    }
    
    //Helpers
    private static User getUser(final Id profileId,Final Boolean isInsert) {
        User u = new User(
            Phone = Randomutility.getString(10),
            FirstName = Randomutility.getString(4),
            LastName = Randomutility.getString(4),
            Username = Randomutility.getString(8)+'@finleap.com',
            Email = Randomutility.getString(6)+'@finleap.com',
            Alias = Randomutility.getString(4),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            ProfileId = profileId,
            LanguageLocaleKey = 'en_US'
        );
        if(isInsert) insert u;
        return u;
    }
    
    private static Account getAccount(Final String recordTypeId,Final Boolean isInsert){
        Account acc=new Account(
        	Name=Randomutility.getString(7),
            Country__c='Germany',
            Legal_Form__c='KYC',
            Rating='A',
            Customer_Type__c='Other',
            RecordTypeId=recordTypeId
        );
        if(isInsert) insert acc;
        return acc;
    }
    
    private static Contact getContact(Final String recordTypeId,Final String accountId,Final Boolean isInsert){
        Contact con=new Contact(
            LastName=Randomutility.getString(7),
            Email=Randomutility.getString(4)+'@finleap.com',
            AccountId=accountId
        );
        if(isInsert) insert con;
        return con;
        
    }
    
    private static Opportunity getOpportunity(Final String recordTypeId,Final String accountId,Final Boolean isInsert){
        Opportunity opp=new Opportunity();
        opp.Name=Randomutility.getString(4);
        opp.AccountId=accountId;
        opp.StageName='Qualifying';
        opp.CloseDate=Date.today();
        opp.Finleap_Company__c='Finleap Connect';
        opp.Product_Vertical__c='None';
        opp.RecordTypeId=recordTypeId;
        if(isInsert) insert opp;
        return opp;
    }
    private static OpportunityContactRole getOpportunityContactRole(String contactId,String oppId,Boolean isInsert){
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = contactId;
        ocr.OpportunityId = oppId;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
       	if(isInsert) insert ocr;
        return ocr;
    }
   
}